# Generated by Django 4.2.3 on 2023-08-19 21:42

from django.db import migrations, models
import filmsai.models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='pub_date',
            field=models.DateTimeField(default=filmsai.models.default_datetime),
        ),
    ]
